### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by femtotrader** [JuliaFinance/MarketObservables.jl#2]
Hi @roshii ,

could you add a basic unit test (1 == 1) and set up Travis ?

Kind regards

**Comment by roshii** [comment]
Hello @femtotrader :)

I do not have access to settings...

@EricForgy how do you want to tackle this?
Should @JuliaFinance/crypto get admin access to relevant repo ? Shall we create an admin team ? Any other suggestion ?

**Comment by femtotrader** [comment]
A owner of https://github.com/JuliaFinance/ (@EricForgy @felipenoris @simonbyrne @TotalVerb) need to go to https://travis-ci.com/organizations/JuliaFinance/repositories to enable CI

**Comment by roshii** [comment]
Oh yes correct, I was thinking GitLab

**Comment by femtotrader** [comment]
Last year I personally moved all my CI setup from https://travis-ci.org/ to https://travis-ci.com/

see https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

maybe this should be done in JuliaFinance also

**Comment by EricForgy** [comment]
Hi guys 👋 

Getting caught up here (I'm in Manila so time zone is a challenge sometimes 😅). Is everything ok now? Do you need me to do anything?

**Comment by roshii** [comment]
> Is everything ok now? 

Yes, CI is enabled, test is passing :)
Thanks again!
