### ISSUE TITLE
Use test_* filenames for unit test files

### ISSUE THREAD

**Issue by femtotrader** [JuliaFinance/MarketObservables.jl#4]
https://github.com/JuliaFinance/MarketObservables.jl/blob/392499db9d871707a65f550f481239c275dfc9e6/test/runtests.jl#L6

maybe test files name should start with `test_` so you can automatically run all `test_*`

see
https://github.com/JuliaCollections/DataStructures.jl/blob/master/test/runtests.jl

**Comment by femtotrader** [comment]
using [Glob](https://github.com/vtjnash/Glob.jl) can help

**Comment by roshii** [comment]
Good suggestion, thanks.
I'm pushing an update

**Comment by roshii** [comment]
Please review code and merge if good with you.

I propose we review each-other code like this: one does the pull request, the other merges it.

**Comment by femtotrader** [comment]
I'm fine with this idea... but I can't merge PR
Ping @EricForgy

**Comment by roshii** [comment]
@femtotrader please try again, I just set @JuliaFinance/crypto team as admin of this repo

**Comment by femtotrader** [comment]
https://github.com/JuliaFinance/MarketObservables.jl/pull/7 merged! thanks for setting but I didn't saw the travis status in the PR.

Looking at https://travis-ci.com/JuliaFinance/MarketObservables.jl/jobs/195182542
it's unclear to me if tests are really running (I think star (`*`) is missing in `test_*`)

**Comment by roshii** [comment]
Good catch, `*` is indeed required
I did commit directly to master
